import { parseVttOrSrt } from './captions';
import type { ExtensionOptions, Segment } from '../../domain/types';

interface RutubeVideoMeta {
  title?: string;
  duration?: number;
  length?: number;
}

export interface RutubeSubtitleTrack {
  code?: string;
  lang?: string;
  language?: string;
  file?: string;
  url?: string;
  langTitle?: string;
  is_autogenerated?: boolean;
}

const RUTUBE_FETCH_HEADERS: HeadersInit = {
  Referer: 'https://rutube.ru/',
  Accept: 'application/json, text/plain, */*',
};

function rutubeOptionsQuery(pageUrl?: string): string {
  const qs = new URLSearchParams({ format: 'json' });
  if (!pageUrl) return qs.toString();
  try {
    const p = new URL(pageUrl).searchParams.get('p');
    if (p) qs.set('p', p);
  } catch {
    /* ignore */
  }
  return qs.toString();
}

function normalizeRutubeTracks(raw: unknown): RutubeSubtitleTrack[] {
  if (Array.isArray(raw)) return raw as RutubeSubtitleTrack[];
  if (raw && typeof raw === 'object') {
    const o = raw as Record<string, unknown>;
    if (Array.isArray(o.results)) return o.results as RutubeSubtitleTrack[];
    if (Array.isArray(o.captions)) return o.captions as RutubeSubtitleTrack[];
  }
  return [];
}

function pickRutubeTrack(
  tracks: RutubeSubtitleTrack[],
  prefer: ExtensionOptions['captionLanguage'],
): RutubeSubtitleTrack | null {
  if (!tracks.length) return null;
  const code = (t: RutubeSubtitleTrack) =>
    (t.code ?? t.lang ?? t.language ?? 'ru').split('-')[0];
  if (prefer === 'ru') {
    return tracks.find((t) => code(t) === 'ru') ?? tracks[0];
  }
  if (prefer === 'en') {
    return tracks.find((t) => code(t) === 'en') ?? tracks[0];
  }
  return tracks.find((t) => code(t) === 'ru') ?? tracks.find((t) => code(t) === 'en') ?? tracks[0];
}

async function fetchRutubeJson<T>(url: string): Promise<T | null> {
  const res = await fetch(url, {
    credentials: 'include',
    headers: RUTUBE_FETCH_HEADERS,
  });
  if (!res.ok) return null;
  try {
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

interface RutubePlayOptions {
  captions?: RutubeSubtitleTrack[];
  effective_video?: string;
  duration?: number;
}

/** Субтитры из play/options (основной источник, как в yt-dlp). */
async function fetchTracksFromPlayOptions(
  videoId: string,
  pageUrl?: string,
): Promise<RutubeSubtitleTrack[]> {
  const query = rutubeOptionsQuery(pageUrl);
  const options = await fetchRutubeJson<RutubePlayOptions>(
    `https://rutube.ru/api/play/options/${videoId}/?${query}`,
  );
  let tracks = normalizeRutubeTracks(options?.captions);
  const effective = options?.effective_video;
  if (!tracks.length && effective && effective !== videoId) {
    const alt = await fetchRutubeJson<RutubePlayOptions>(
      `https://rutube.ru/api/play/options/${effective}/?${query}`,
    );
    tracks = normalizeRutubeTracks(alt?.captions);
  }
  return tracks;
}

/** Устаревший эндпоинт; часто 404, хотя captions есть в play/options. */
async function fetchTracksFromSubtitlesApi(videoId: string): Promise<RutubeSubtitleTrack[]> {
  const body = await fetchRutubeJson<unknown>(
    `https://rutube.ru/api/video/${videoId}/subtitles/?format=json`,
  );
  return normalizeRutubeTracks(body);
}

export async function loadRutubeTrackFile(
  track: RutubeSubtitleTrack,
): Promise<Segment[]> {
  const fileUrl = track.file ?? track.url;
  if (!fileUrl) throw new Error('Нет URL файла субтитров Rutube');

  const vttRes = await fetch(fileUrl, {
    credentials: 'include',
    headers: { Referer: 'https://rutube.ru/' },
  });
  if (!vttRes.ok) {
    throw new Error(`Не удалось загрузить субтитры Rutube (${vttRes.status})`);
  }

  const segments = parseVttOrSrt(await vttRes.text());
  if (!segments.length) throw new Error('Субтитры Rutube пустые');
  return segments;
}

export async function resolveRutubeTracks(
  videoId: string,
  pageUrl?: string,
): Promise<RutubeSubtitleTrack[]> {
  const fromOptions = await fetchTracksFromPlayOptions(videoId, pageUrl);
  if (fromOptions.length) return fromOptions;
  return fetchTracksFromSubtitlesApi(videoId);
}

export async function fetchRutubeCaptions(
  videoId: string,
  preferLang: ExtensionOptions['captionLanguage'],
  pageUrl?: string,
): Promise<{ segments: Segment[]; language: string; title?: string; durationSec: number }> {
  const metaRes = await fetch(`https://rutube.ru/api/video/${videoId}/?format=json`, {
    credentials: 'include',
    headers: RUTUBE_FETCH_HEADERS,
  });
  if (!metaRes.ok) {
    throw new Error(`Rutube: видео недоступно (${metaRes.status})`);
  }
  const meta = (await metaRes.json()) as RutubeVideoMeta;
  const durationSec = meta.duration ?? meta.length ?? 0;
  const title = meta.title;

  const tracks = await resolveRutubeTracks(videoId, pageUrl);
  const track = pickRutubeTrack(tracks, preferLang);
  if (!track) {
    throw new Error(
      'Нет файла субтитров Rutube для этого ролика. Режим «Субтитры видео» не читает голос — Rutube не отдал дорожку.',
    );
  }

  const segments = await loadRutubeTrackFile(track);
  const language = track.code ?? track.lang ?? track.language ?? 'ru';
  return { segments, language, title, durationSec };
}
